### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by enriquein** [OllieDay/Daffer#1]
Would it be desirable to add support for transactions? Is this use case considered out of scope for daffer? I understand that this may break the nice and tidy API daffer provides, but just wondering if it would be possible to add that.

Thank you for such a nice wrapper.

**Comment by OllieDay** [comment]
I think it would be a nice addition and it makes sense to include it since it's part of the Dapper API. The other optional arguments (commandTimeout and commandType) should be added as well for completeness.

This would mean changing the library to use a builder pattern for queries:

```f#
let builder =
    sql "select x from y where z = @z"
    |> withParams ["z" => 1]
    |> withConnection connection
    |> withTransaction transaction
    |> withCommandTimeout commandTimeout
    |> withCommandType commandType

let user = query<User> builder
```

It's not as succinct for simple use cases but does make things more complete. Do you have any suggestions for an alternative approach?

**Comment by enriquein** [comment]
I like the approach, because to be honest I didn't have much of an initial idea on how to implement the additional parameter. For simple cases the current usage would be a tad bit different but not by too much, i think.
```fsharp
let user = query<User> connection "select x from y where z = @z" ["z" => 1]
```
This would change to (trying to stick to a single line of code):
```fsharp
let user = sql "select x from y where z = @z" |> withParams ["z" => 1] |> withConnection connection |> query<User>
```
Or indented:
```fsharp
let user = 
     sql "select x from y where z = @z" 
     |> withParams ["z" => 1] 
     |> withConnection connection 
     |> query<User>
```
I think I like it. It's a good compromise in order to be able to provide Dapper's optional parameters. Another thing that occurs to me is that there's also the possibility of leaving the old APIs for simple cases and the builder for when you need the extra stuff.

**Comment by OllieDay** [comment]
This has now been implemented and a new version pushed to NuGet.

The existing API was left intact (good suggestion) and there's a new `Builder` module that can optionally be used if required. The end result is a little different in that the mandatory arguments (`connection`, `sql`, `parameters`) are not part of the builder API as I figured it would be best to keep the wrapper functions in the existing API and the new builder module  the same.

```fsharp
let user =
    Builder.create ()
        |> Builder.addTransaction transaction
        |> Builder.addCommandTimeout 1000
        |> Builder.addCommandType CommandType.StoredProcedure
        |> Builder.addBuffered false
        |> Builder.query<User> connection "SELECT * FROM Users WHERE Id = @Id" ["id" => 1]
```

**Comment by enriquein** [comment]
Excellent job! I implemented the changes in our solution, and I really like how the new Builder API turned out. 

I had a bit of an edge case where one of the functions we expose to hide the data access allows passing in an optional transaction object, and that transaction then gets passed straight into Dapper. Solved it by adding a small `addTransactionMaybe` function to the `Builder` module that just passes the optional transaction to the `Build` record. I'm not sure if this is something that would be interesting to other users, and seeing how easy it is to open up the module and add functions, I think this is an OK solution for the edge case.

Thank you for taking the time to implement this ❤️

**Comment by OllieDay** [comment]
Could you provide an example? Not sure I follow exactly what you mean.

**Comment by enriquein** [comment]
To clarify upfront, I don't think this is something that is missing from the API. This is probably a thing very specific to us and this project. In the project I have the data access functionality hidden behind a bunch of class methods, which make up the data API for this app. Some of the methods are also called by other API class methods (some from other classes), and in some cases may require the use transactions. To allow for both usage scenarios, I made the transaction object an optional parameter of these methods. With the way optional parameters work in F#, and how the original call to Dapper works, a call to `Execute` would look something like:

```fsharp
connection.Execute(query, {| someParam = someParamValue |}, transaction = defaultArg transaction null) |> ignore
```

So to change this code to use the new `Builder` I had a few options. Keeping in mind  that `transaction: IDbTransaction option`: 
1) Split the logic into conditional branches:
```fsharp
match transaction with
| Some tran ->
    Builder.create()
    |> Builder.addTransaction tran
    |> Builder.execute connection query ["someParam" => someParamValue
    |> ignore
| None -> 
    Builder.create()
    |> Builder.execute connection query ["someParam" => someParamValue
    |> ignore
```
2) Have a way to pass the option<IDbTransaction> object straight to the `Builder`:
```fsharp
    Builder.create()
    |> Builder.addTransactionMaybe transaction
    |> Builder.execute connection query ["someParam" => someParamValue
    |> ignore
```
3) Inlining some function call that would evaluate the optional value and call `Builder.addTransaction`

I went with #2. Adding `addTransactionMaybe` to the `Builder` was super trivial. I just created a new file in our project and added this:
```fsharp
namespace Daffer
open System.Data

module Builder =
    let addTransactionMaybe (maybeTransaction: Option<IDbTransaction>) (build: Builder.Build) =
        { build with Transaction = maybeTransaction }
```

I wasn't sure if I should mention this or not, mostly because it seems to be a very "us" situation. I don't know how many people out there would find something like this useful.

**Comment by OllieDay** [comment]
I'll leave it out to keep things as close to the underlying Dapper API.

There's another way to achieve it without a wrapper function since passing `null` to Dapper is fine as that's the default value anyway:

```fsharp
Builder.create()
    |> Builder.addTransaction (Option.defaultValue null transaction)
    |> Builder.execute connection query ["someParam" => someParamValue
    |> ignore
```

**Comment by enriquein** [comment]
You're absolutely right. I think that's the way to go. Thanks for the suggestion!
